// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.dotnet.samples.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class EnrichedOrder : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""EnrichedOrder"",""namespace"":""com.dotnet.samples.avro"",""fields"":[{""name"":""productName"",""type"":""string""},{""name"":""productId"",""type"":""int""},{""name"":""customerName"",""type"":""string""},{""name"":""customerId"",""type"":""int""},{""name"":""orderId"",""type"":""int""}]}");
		private string _productName;
		private int _productId;
		private string _customerName;
		private int _customerId;
		private int _orderId;

        public EnrichedOrder(Product product, Customer customer, Order order)
        {
			_productName = product.name;
			_productId = product.id;
			_customerId = customer.id;
			_customerName = customer.name;
			_orderId = order.id;
        }

        public virtual Schema Schema
		{
			get
			{
				return EnrichedOrder._SCHEMA;
			}
		}
		public string productName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		public int productId
		{
			get
			{
				return this._productId;
			}
			set
			{
				this._productId = value;
			}
		}
		public string customerName
		{
			get
			{
				return this._customerName;
			}
			set
			{
				this._customerName = value;
			}
		}
		public int customerId
		{
			get
			{
				return this._customerId;
			}
			set
			{
				this._customerId = value;
			}
		}
		public int orderId
		{
			get
			{
				return this._orderId;
			}
			set
			{
				this._orderId = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.productName;
			case 1: return this.productId;
			case 2: return this.customerName;
			case 3: return this.customerId;
			case 4: return this.orderId;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.productName = (System.String)fieldValue; break;
			case 1: this.productId = (System.Int32)fieldValue; break;
			case 2: this.customerName = (System.String)fieldValue; break;
			case 3: this.customerId = (System.Int32)fieldValue; break;
			case 4: this.orderId = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
