// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.dotnet.samples.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class PageView : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"PageView\",\"namespace\":\"com.dotnet.samples.avro\",\"fields\"" +
				":[{\"name\":\"user\",\"type\":\"string\"},{\"name\":\"url\",\"type\":\"string\"}]}");
		private string _user;
		private string _url;
		public virtual Schema Schema
		{
			get
			{
				return PageView._SCHEMA;
			}
		}
		public string user
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				this._url = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.user;
			case 1: return this.url;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.user = (System.String)fieldValue; break;
			case 1: this.url = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
