# This file is managed by ServiceBot plugin - Semaphore. The content in this file is created using a common
# template and configurations in service.yml.
# Modifications in this file will be overwritten by generated content in the nightly run.
# For more information, please refer to the page:
# https://confluentinc.atlassian.net/wiki/spaces/Foundations/pages/2871296194/Add+SemaphoreCI
apiVersion: v1alpha
kind: Project
metadata:
  name: kafka-streams-examples
  description: ""
spec:
  visibility: private
  repository:
    url: git@github.com:confluentinc/kafka-streams-examples.git
    run_on:
    - branches
    - pull_requests
    pipeline_file: .semaphore/semaphore.yml
    integration_type: github_app
    status:
      pipeline_files:
      - path: .semaphore/semaphore.yml
        level: pipeline
    whitelist:
      branches:
      - 'master'
      - 'main'
      - '/^\d+\.\d+\.x$/'
      - '/^\d+\.\d+\.\d+-cp\d+-rc\d+$/'
      - '/^\d+\.\d+\.\d+-rc\d+$/'
      - '/^gh-readonly-queue.*/'
  custom_permissions: true
  debug_permissions:
  - empty
  - default_branch
  - non_default_branch
  - pull_request
  - forked_pull_request
  - tag
  attach_permissions:
  - default_branch
  - non_default_branch
  - pull_request
  - forked_pull_request
  - tag
  tasks:
  - name: cp-dockerfile-build
    scheduled: False
    branch: "master"
    pipeline_file: .semaphore/cp_dockerfile_build.yml
    parameters:
    - name: CONFLUENT_VERSION
      required: True
    - name: PACKAGES_URL
      required: False
    - name: PACKAGES_MAVEN_URL
      required: False
    - name: PACKAGING_BUILD_NUMBER
      required: True
    - name: ALLOW_UNSIGNED
      required: False
      default_value: "False"
      options:
       - True
       - False
    - name: CONFLUENT_DEB_VERSION
      required: False
      default_value: "1"
  - name: cp-dockerfile-promote
    scheduled: False
    branch: "master"
    pipeline_file: .semaphore/cp_dockerfile_promote.yml
    parameters:
    - name: CONFLUENT_VERSION
      required: True
    - name: IMAGE_REVISION
      required: True
      default_value: "1"
    - name: UPDATE_LATEST_TAG
      required: True
    - name: PACKAGING_BUILD_NUMBER
      required: True
    - name: PROMOTE_OS_TYPE
      required: True
      options:
       - deb
       - ubi
